package ru.ylab.enumerated;

public enum AuditionEventType {
    SESSION_START,
    SESSION_END,
    REGISTRATION,
    READINGS_SUBMISSION,
    NEW_METER_TYPE_ADDITION,
    SINGLE_SUBMISSION_ACQUIRE,
    SUBMISSION_HISTORY_ACQUIRE
}
